name: release

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'tag_name'
                required: true
                default: 'vx.x.x'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1
        with:
          go_version: "1.19"
